version: '3'
services:
  rdf4j:
    image: tibblue/tese-rdf4j:latest
    build:
      context: ./rdf4j
      dockerfile: Dockerfile
    environment:
      - RDF4J_DATA=/root/.RDF4J
    restart: on-failure
    ports:
      - "8080:8080"
  frontend:
    image: tibblue/tese-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    links:
      - rdf4j
    ports:
      - "8000:8000"
