version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - mongoData:/data/db
      # - /mnt/c/Users/KIKO/Desktop/GIT/TESE/mongo/mongoData:/data/db
    ports:
      - "27017:27017"
  rdf4j:
    image: tibblue/tese-rdf4j:latest
    environment:
      RDF4J_DATA: ${RDF4J_DATA}
      VUE_APP_RDF4J_PORT: ${VUE_APP_RDF4J_PORT}
    restart: on-failure
    ports:
      - "${VUE_APP_RDF4J_PORT}:8080"
  backend:
    image: tibblue/tese-backend:latest
    environment:
      VUE_APP_RDF4J_PORT: ${VUE_APP_RDF4J_PORT}
      VUE_APP_BACKEND_PORT: ${VUE_APP_BACKEND_PORT}
      VUE_APP_FRONTEND_PORT: ${VUE_APP_FRONTEND_PORT}
    links:
      - mongo
      - rdf4j
    restart: on-failure
    ports:
      - "${VUE_APP_BACKEND_PORT}:5000"
  frontend:
    image: tibblue/tese-frontend:latest
    environment:
      VUE_APP_BACKEND_PORT: ${VUE_APP_BACKEND_PORT}
      VUE_APP_FRONTEND_PORT: ${VUE_APP_FRONTEND_PORT}
    links:
      - backend
    restart: on-failure
    ports:
      - "${VUE_APP_FRONTEND_PORT}:8000"
volumes:
  mongoData:
