version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - mongoData:/data/db
    environment:
      MONGO_PORT: ${MONGO_PORT}
    ports:
      - "${MONGO_PORT}:27017"
    restart: on-failure
  rdf4j:
    image: tibblue/tese-rdf4j:latest
    environment:
      RDF4J_DATA: ${RDF4J_DATA}
      RDF4J_PORT: ${RDF4J_PORT}
    ports:
      - "${RDF4J_PORT}:8080"
    restart: on-failure
  backend:
    image: tibblue/tese-backend:latest
    environment:
      RDF4J_PORT: ${RDF4J_PORT}
      MONGO_PORT: ${MONGO_PORT}
      VUE_APP_BACKEND_PORT: ${VUE_APP_BACKEND_PORT}
    links:
      - mongo
      - rdf4j
    ports:
      - "${VUE_APP_BACKEND_PORT}:5000"
    restart: on-failure
  # frontend:
  #   image: tibblue/tese-frontend:latest
  #   environment:
  #     VUE_APP_BACKEND_PORT: ${VUE_APP_BACKEND_PORT}
  #     VUE_APP_FRONTEND_PORT: ${VUE_APP_FRONTEND_PORT}
  #   links:
  #     - backend
  #   ports:
  #     - "${VUE_APP_FRONTEND_PORT}:8000"
  #   restart: on-failure
volumes:
  mongoData:
