version: '3'
services:
  rdf4j:
    image: tibblue/tese-rdf4j:latest
    build:
      context: ./../rdf4j
      dockerfile: Dockerfile
    env_file: './.env'
    restart: on-failure
    ports:
      - "${VUE_APP_RDF4J_PORT}:8080"
  frontend:
    image: tibblue/tese-frontend:latest
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    links:
      - rdf4j
    ports:
      - "${VUE_APP_FRONTEND_PORT}:8000"
