
startup:
	export JAVA_OPTS='-Dorg.eclipse.rdf4j.appdata.basedir=/mnt/c/Users/KIKO/Desktop/GIT/TESE/rdf4j/rdf_save_state' && \
# 	echo $$JAVA_OPTS && \
	cd programs/apache-tomcat-9.0.22/bin/ && \
	./startup.sh


shutdown:
	cd programs/apache-tomcat-9.0.22/bin/ && \
	./shutdown.sh

