
startup:
	export JAVA_OPTS='-Dorg.eclipse.rdf4j.appdata.basedir=rdf_save_state' #changes default save folder
	cd programs/apache-tomcat-9.0.22/bin/ && \
	./startup.sh


shutdown:
	cd programs/apache-tomcat-9.0.22/bin/ && \
	./shutdown.sh