---
openapi: '3.0.0'
info:
  version: 1.0.0
  title: OntoWorks Application API
  description: OntoWorks Backend Application API documentation
  contact:
    name: Francisco Oliveira
    email: a78416@alunos.uminho.pt
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://epl.di.uminho.pt:5000/api
    description: Main server
  - url: http://localhost:5000/api
    description: Testing server

components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
  schemas:
    User:
      required:
      - name
      - email
      - password
      properties:
        name:
          type: string
          example: "TestUser"
        email:
          type: string
          uniqueItems: true
          example: "test@email"
        password:
          type: string
          example: "testpass"
    Repository:
      required:
      - id
      - name
      - owner_email
      properties:
        id:
          type: string
          uniqueItems: true
        name:
          type: string
        owner_email:
          type: string
    SavedQuery:
      required:
      - user_email
      - name
      - query
      properties:
        user_email:
          type: string
          uniqueItems: true
        name:
          type: string
          uniqueItems: true
        query:
          type: string
        repoID:
          type: string


tags:
- name: Auth
  description: Requests related to User Authentication
- name: RDF4J
  description: Requests related to RDF4J Server
- name: Mongo
  description: Requests related to MongoDB
paths:
  "/auth/signup":
    post:
      tags:
      - Auth
      summary: Create new user account
      description: Create new user account.
      requestBody:
        description: User account details.
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: New user is created, and returns JSON user object
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/User"
        '500':
          description: Creation failed. Likely duplicate key (already used email)
  "/auth/login":
    post:
      tags:
      - Auth
      summary: Login with user account
      description: Login with user account. Grants access to additional features.
      requestBody:
        description: Login credentials.
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
              # example:
              #   email: "kiko"
              #   password: "kiko"
      responses:
        '200':
          description: JWT access token. Will be required in some requests for Authorization.
        '404':
          description: Login failed. Likely wrong email ou password
  "/auth/delete/{email}":
    delete:
      tags:
      - Auth
      summary: Delete user account by email
      description: |
        Delete user account with the specified email.
        Only the user himself or a admin can delete a account.
      security:
        - bearerAuth: []
      parameters:
      - in: path
        required: true
        name: email
        description: Account email to delete
        schema:
          type: string
        # allowReserved: true
      responses:
        default:
          description: TODO
        '200':
          description: Account deleted
        '401':
          description: Unauthorized
  "/auth/user":
    get:
      tags:
      - Auth
      deprecated: true
      security:
        - bearerAuth: []
      responses:
        default:
          description: Debug


  "/rdf4j":
    get:
      tags:
      - RDF4J
      summary: Login with user account
      description: Login with user account. Grants access to additional features.
      responses:
        default:
          description: TODO
  "/mongo":
    get:
      tags:
      - Mongo
      summary: Login with user account
      description: Login with user account. Grants access to additional features.
      responses:
        default:
          description: TODO
