---
openapi: '3.0.0'
info:
  version: 1.0.0
  title: OntoWorks Application API
  description: OntoWorks Backend Application API documentation
  contact:
    name: Francisco Oliveira
    email: a78416@alunos.uminho.pt
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://epl.di.uminho.pt:8001/api
    description: Main server
  - url: http://localhost:5000/api
    description: Testing server

tags:
- name: Auth
  description: Requests related to User Authentication
- name: RDF4J
  description: Requests related to RDF4J Server
- name: Mongo
  description: Requests related to MongoDB
paths:
  "/auth/signup":
    post:
      tags:
      - Auth
      summary: Create new user account
      description: Create new user account.
      requestBody:
        description: User account details.
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - name
                - email
                - password
      responses:
        '200':
          description: New user is created, and returns JSON user object
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/User"
        '500':
          description: Creation failed. Likely duplicate key (already used email)
  "/auth/login":
    post:
      tags:
      - Auth
      summary: Login with user account
      description: |
        Login with user account.
        Returns JWT token to be used as authorization for some requests and User name and email.
      requestBody:
        description: Login credentials.
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
              # example:
              #   email: "kiko"
              #   password: "kiko"
      responses:
        '200':
          description: JWT access token and User info. JWT will be required in some requests for Authorization.
        '404':
          description: Login failed. Likely wrong email ou password.
  "/auth/user":
    get:
      tags:
      - Auth
      summary: Get user info from JWT
      description: |
        Decrypts JWT payload, returning some user account information.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Information returned.
        '401':
          description: Unauthorized
  "/auth/delete/{email}":
    delete:
      tags:
      - Auth
      summary: Delete user account by email
      description: |
        Delete user account with the specified email.
        Only the user himself or a admin can delete a account.
      security:
        - bearerAuth: []
      parameters:
      - in: path
        required: true
        name: email
        description: Account email to delete
        schema:
          type: string
      responses:
        '200':
          description: Account deleted
        '401':
          description: Unauthorized
        # default:
        #   description: Email doesn't exist

  # RDF4J SECTION
  "/rdf4j":
    get:
      tags:
      - RDF4J
      deprecated: true
      summary: TODO
      description: TODO
      responses:
        default:
          description: TODO
  "/rdf4j/management/listRepos":
    get:
      tags:
      - RDF4J
      summary: List Repositories
      description: Returns all existing repositories.
      responses:
        '200':
          description: Request success
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    readable:
                      type: object
                      properties:
                        datatype:
                          type: string
                        type:
                          type: string
                        value:
                          type: boolean
                    id:
                      type: object
                      properties:
                        type:
                          type: string
                        value:
                          type: boolean
                    title:
                      type: object
                      properties:
                        type:
                          type: string
                        value:
                          type: boolean
                    uri:
                      type: object
                      properties:
                        type:
                          type: string
                        value:
                          type: boolean
                    writable:
                      type: object
                      properties:
                        datatype:
                          type: string
                        type:
                          type: string
                        value:
                          type: boolean
        '400':
          description: Bad request
  "/rdf4j/management/create":
    post:
      tags:
      - RDF4J
      summary: Create a new Repository
      description: |
        Create a new Repository.
        Creating a repository with a Repository ID that already exists will overwrite the old one,
        likely resulting is data loss.
      requestBody:
        description: Login credentials.
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                type:
                  type: string
                  enum: ["memory", "memory-rdfs-dt", "native", "native-rdfs-dt"]
                  default: memory
                Repository ID:
                  type: string
                Repository title:
                  type: string
                # Persist:
                #   type: string
                # Sync Delay:
                #   type: string
              # required:
              #   - type
              #   - Repository ID
              #   - Repository title
              example:
                type: "memory-rdfs-dt"
                Repository ID: "test"
                Repository title: "test"
      responses:
        '200':
          description: Create success
        '400':
          description: Bad request
        default:
          description: TODO (already existing repo ID)
  "/rdf4j/management/delete/{repository}":
    delete:
      tags:
      - RDF4J
      summary: Delete a Repository
      # description: Delete a Repository
      parameters:
      - in: path
        required: true
        name: repository
        description: Target Repository
        schema:
          type: string
          example: "test"
      responses:
        '200':
          description: Delete success
        '400':
          description: Bad request (or the repository does not exist)
  "/rdf4j/management/delete/{repository}/statements":
    delete:
      tags:
      - RDF4J
      summary: Clear all Repository statements/triples
      # description: Clear all Repository statements/triples
      parameters:
      - in: path
        required: true
        name: repository
        description: Target Repository
        schema:
          type: string
          example: "test"
      responses:
        '200':
          description: Clear success
        '400':
          description: Bad request (or the repository does not exist)
  "/rdf4j/repository/{repository}/explicit":
    get:
      tags:
      - RDF4J
      summary: Explicit triples count
      description: Returns the number of explicit triples in the repository.
      parameters:
      - in: path
        required: true
        name: repository
        description: Target Repository
        schema:
          type: string
      responses:
        '200':
          description: Request success
        '400':
          description: Bad request
  "/rdf4j/repository/{repository}/total":
    get:
      tags:
      - RDF4J
      summary: Total triples count
      description: Returns the total (explicit+implicit) number of triples in the repository.
      parameters:
      - in: path
        required: true
        name: repository
        description: Target Repository
        schema:
          type: string
      responses:
        '200':
          description: Request success
        '400':
          description: Bad request
  "/rdf4j/repository/{repository}/triples":
    get:
      tags:
      - RDF4J
      summary: Explicit and Implicit triples count and Expansion ratio
      description: Returns the number of explicit and implicit triples in the repository and the expansion ratio.
      parameters:
      - in: path
        required: true
        name: repository
        description: Target Repository
        schema:
          type: string
      responses:
        '200':
          description: Request success
        '400':
          description: Bad request
  "/rdf4j/repository/{repository}/namespaces":
    get:
      tags:
      - RDF4J
      summary: Repository Namespaces
      description: Returns the repository namespaces.
      parameters:
      - in: path
        required: true
        name: repository
        description: Target Repository
        schema:
          type: string
      responses:
        '200':
          description: Request success
        '400':
          description: Bad request
  "/rdf4j/repository/{repository}/contexts":
    get:
      tags:
      - RDF4J
      summary: Repository contexts
      description: Returns the repository contexts.
      parameters:
      - in: path
        required: true
        name: repository
        description: Target Repository
        schema:
          type: string
      responses:
        '200':
          description: Request success
        '400':
          description: Bad request
  "/rdf4j/query/{repository}":
    get:
      tags:
      - RDF4J
      summary: Query a Repository
      description: |
        Run a SPARQL query in a Repository.
        Because it is a GET request the query size is limited. Use the POST if needed.
      parameters:
      - in: path
        required: true
        name: repository
        description: Repository to be queried
        schema:
          type: string
      - in: query
        required: true
        name: query
        description: SPARQL query to run
        schema:
          type: string
          example: "select * where { ?s ?p ?o } limit 20"
      - in: query
        name: infer
        description: Returns infered triples? (default true)
        schema:
          type: string
          example: "true"
      responses:
        '200':
          description: Query successful
        '400':
          description: Bad request
    post:
      tags:
      - RDF4J
      summary: Query a Repository
      description: |
        Run a SPARQL query in a Repository.
      parameters:
      - in: path
        required: true
        name: repository
        description: Repository to be queried
        schema:
          type: string
      requestBody:
        # description: Login credentials.
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: SPARQL query to run
                infer:
                  type: string
                  description: Returns infered triples? (default true)
              required:
                - query
              example:
                query: "select * where { ?s ?p ?o } limit 20"
                infer: "true"
      responses:
        '200':
          description: Query successful
        '400':
          description: Bad request

  # MONGO SECTION
  "/mongo":
    get:
      tags:
      - Mongo
      deprecated: true
      summary: TODO
      description: TODO
      responses:
        default:
          description: TODO
  "/users":
    get:
      tags:
      - Mongo
      summary: Users list
      description: Returns a JSON list with all the users.
      responses:
        '200':
          description: Operation successful
          # content:
          #   application/json:
          #     schema:
          #       $ref: '#/components/schemas/User'
        default:
          description: Unexpected error
    post:
      tags:
      - Mongo
      summary: TODO
      description: TODO
      responses:
        default:
          description: TODO
  "/users/{email}":
    get:
      tags:
      - Mongo
      summary: TODO
      description: TODO
      parameters:
      - in: path
        required: true
        name: email
        description: Account email
        schema:
          type: string
      responses:
        default:
          description: TODO
    delete:
      tags:
      - Mongo
      summary: TODO
      description: TODO
      parameters:
      - in: path
        required: true
        name: email
        description: Account email
        schema:
          type: string
      responses:
        default:
          description: TODO
  "/users/{email}/password":
    put:
      tags:
      - Mongo
      summary: TODO
      description: TODO
      parameters:
      - in: path
        required: true
        name: email
        description: Account email
        schema:
          type: string
      responses:
        default:
          description: TODO


components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
  schemas:
    User:
      required:
      - name
      - email
      - password
      properties:
        name:
          type: string
          example: "test"
        email:
          type: string
          uniqueItems: true
          example: "test@email"
        password:
          type: string
          example: "test"
    Repository:
      required:
      - id
      - name
      - owner_email
      properties:
        id:
          type: string
          uniqueItems: true
        name:
          type: string
        owner_email:
          type: string
    SavedQuery:
      required:
      - user_email
      - name
      - query
      properties:
        user_email:
          type: string
          uniqueItems: true
        name:
          type: string
          uniqueItems: true
        query:
          type: string
        repoID:
          type: string
